version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: mantis-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bugtracker
      MYSQL_USER: mantis
      MYSQL_PASSWORD: mantisbt
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mantis-net

  mantisbt:
    image: vimagick/mantisbt
    container_name: mantis-app
    ports:
      - "8989:80"
    environment:
      - DB_TYPE=mysqli
      - DB_HOST=db
      - DB_NAME=bugtracker
      - DB_USER=mantis
      - DB_PASSWORD=mantisbt
    depends_on:
      - db
    networks:
      - mantis-net

volumes:
  db_data:

networks:
  mantis-net:
